#include "kernel/kernel.h"
#include "kernel/memory.h"
#include "kernel/interrupts.h"
#include "kernel/timer.h"
#include "kernel/process.h"
#include "drivers/vga.h"
#include "drivers/keyboard.h"
#include "drivers/serial.h"
#include "drivers/ata.h"
#include "gui/graphics.h"
#include "gui/window.h"
#include "fs/fat32.h"
#include "libc/stdio.h"
#include "libc/string.h"

struct multiboot_info *mbi;
uint32_t initial_esp;

// GDT structures
struct gdt_entry {
    uint16_t limit_low;
        uint16_t base_low;
            uint8_t base_middle;
                uint8_t access;
                    uint8_t granularity;
                        uint8_t base_high;
                        } __attribute__((packed));

                        struct gdt_ptr {
                            uint16_t limit;
                                uint32_t base;
                                } __attribute__((packed));

                                struct gdt_entry gdt[5];
                                struct gdt_ptr gp;

                                static void gdt_set_gate(int num, uint32_t base, uint32_t limit, uint8_t access, uint8_t gran) {
                                    gdt[num].base_low = (base & 0xFFFF);
                                        gdt[num].base_middle = (base >> 16) & 0xFF;
                                            gdt[num].base_high = (base >> 24) & 0xFF;
                                                
                                                    gdt[num].limit_low = (limit & 0xFFFF);
                                                        gdt[num].granularity = ((limit >> 16) & 0x0F);
                                                            
                                                                gdt[num].granularity |= (gran & 0xF0);
                                                                    gdt[num].access = access;
                                                                    }

                                                                    void gdt_install(void) {
                                                                        gp.limit = (sizeof(struct gdt_entry) * 5) - 1;
                                                                            gp.base = (uint32_t)&gdt;
                                                                                
                                                                                    gdt_set_gate(0, 0, 0, 0, 0);                // Null segment
                                                                                        gdt_set_gate(1, 0, 0xFFFFFFFF, 0x9A, 0xCF); // Code segment
                                                                                            gdt_set_gate(2, 0, 0xFFFFFFFF, 0x92, 0xCF); // Data segment
                                                                                                gdt_set_gate(3, 0, 0xFFFFFFFF, 0xFA, 0xCF); // User mode code segment
                                                                                                    gdt_set_gate(4, 0, 0xFFFFFFFF, 0xF2, 0xCF); // User mode data segment
                                                                                                        
                                                                                                            gdt_flush();
                                                                                                            }

                                                                                                            void outb(uint16_t port, uint8_t value) {
                                                                                                                __asm__ volatile ("outb %1, %0" : : "dN" (port), "a" (value));
                                                                                                                }

                                                                                                                uint8_t inb(uint16_t port) {
                                                                                                                    uint8_t ret;
                                                                                                                        __asm__ volatile("inb %1, %0" : "=a" (ret) : "dN" (port));
                                                                                                                            return ret;
                                                                                                                            }

                                                                                                                            void outw(uint16_t port, uint16_t value) {
                                                                                                                                __asm__ volatile ("outw %1, %0" : : "dN" (port), "a" (value));
                                                                                                                                }

                                                                                                                                uint16_t inw(uint16_t port) {
                                                                                                                                    uint16_t ret;
                                                                                                                                        __asm__ volatile ("inw %1, %0" : "=a" (ret) : "dN" (port));
                                                                                                                                            return ret;
                                                                                                                                            }

                                                                                                                                            void kernel_panic(const char *message) {
                                                                                                                                                vga_set_color(vga_entry_color(VGA_COLOR_WHITE, VGA_COLOR_RED));
                                                                                                                                                    printf("\n\nKERNEL PANIC: %s\n", message);
                                                                                                                                                        printf("System halted.\n");
                                                                                                                                                            
                                                                                                                                                                __asm__ volatile ("cli");
                                                                                                                                                                    for (;;) {
                                                                                                                                                                            __asm__ volatile ("hlt");
                                                                                                                                                                                }
                                                                                                                                                                                }

                                                                                                                                                                                void debug_print(const char *message) {
                                                                                                                                                                                    serial_writestring(COM1, message);
                                                                                                                                                                                        serial_writestring(COM1, "\r\n");
                                                                                                                                                                                        }

                                                                                                                                                                                        void debug_print_hex(uint32_t value) {
                                                                                                                                                                                            char hex_str[9];
                                                                                                                                                                                                const char hex_chars[] = "0123456789ABCDEF";
                                                                                                                                                                                                    
                                                                                                                                                                                                        for (int i = 7; i >= 0; i--) {
                                                                                                                                                                                                                hex_str[i] = hex_chars[value & 0xF];
                                                                                                                                                                                                                        value >>= 4;
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                hex_str[8] = '\0';
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                        debug_print(hex_str);
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                        static void test_gui(void) {
                                                                                                                                                                                                                                            // Switch to graphics mode
                                                                                                                                                                                                                                                graphics_init();
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                        // Create a test window
                                                                                                                                                                                                                                                            window_t *window = window_create(50, 50, 200, 150, "Test Window");
                                                                                                                                                                                                                                                                if (window) {
                                                                                                                                                                                                                                                                        window_clear(window, 15); // White background
                                                                                                                                                                                                                                                                                window_draw_rect(window, 10, 10, 50, 30, 1); // Blue rectangle
                                                                                                                                                                                                                                                                                        window_show(window);
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                        printf("GUI test window created successfully!\n");
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                            void kernel_main(uint32_t magic, struct multiboot_info *multiboot_info) {
                                                                                                                                                                                                                                                                                                                // Store multiboot info
                                                                                                                                                                                                                                                                                                                    mbi = multiboot_info;
                                                                                                                                                                                                                                                                                                                        initial_esp = 0; // Will be set by assembly code
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                // Initialize VGA terminal
                                                                                                                                                                                                                                                                                                                                    vga_init();
                                                                                                                                                                                                                                                                                                                                        vga_clear();
                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                // Initialize serial port for debugging
                                                                                                                                                                                                                                                                                                                                                    serial_init(COM1);
                                                                                                                                                                                                                                                                                                                                                        debug_print("Maya OS - Starting kernel...");
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                // Check multiboot magic
                                                                                                                                                                                                                                                                                                                                                                    if (magic != 0x2BADB002) {
                                                                                                                                                                                                                                                                                                                                                                            kernel_panic("Invalid multiboot magic number");
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        printf("Maya OS v0.1.0 - x86 Operating System\n");
                                                                                                                                                                                                                                                                                                                                                                                            printf("Copyright (c) 2024 Maya OS Project\n\n");
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    // Initialize GDT
                                                                                                                                                                                                                                                                                                                                                                                                        gdt_install();
                                                                                                                                                                                                                                                                                                                                                                                                            printf("GDT initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                    // Initialize IDT and enable interrupts
                                                                                                                                                                                                                                                                                                                                                                                                                        idt_install();
                                                                                                                                                                                                                                                                                                                                                                                                                            pic_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                printf("IDT and PIC initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize memory management
                                                                                                                                                                                                                                                                                                                                                                                                                                            pmm_init(multiboot_info);
                                                                                                                                                                                                                                                                                                                                                                                                                                                vmm_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    heap_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Memory management initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Total memory: %d KB\n", pmm_get_total_memory() / 1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Used memory: %d KB\n", pmm_get_used_memory() / 1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize timer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timer_init(100); // 100Hz timer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Timer initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize keyboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            keyboard_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Keyboard initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize ATA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ata_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("ATA controller initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize FAT32 filesystem
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fat32_init(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("FAT32 filesystem initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Initialize process management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            process_init();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Process management initialized.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Test GUI system
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Testing GUI system...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                test_gui();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\nMaya OS initialization complete!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("System ready. Type commands below:\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Available commands: help, clear, memory, reboot\n\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Simple command loop
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            char input_buffer[256];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int buffer_pos = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("maya-os> ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        char c = keyboard_getchar();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (c == '\n') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input_buffer[buffer_pos] = '\0';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Process command
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (strcmp(input_buffer, "help") == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Maya OS Commands:\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("  help    - Show this help message\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("  clear   - Clear the screen\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("  memory  - Show memory information\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("  reboot  - Restart the system\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else if (strcmp(input_buffer, "clear") == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vga_clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (strcmp(input_buffer, "memory") == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Memory Information:\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("  Total: %d KB\n", pmm_get_total_memory() / 1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("  Used: %d KB\n", pmm_get_used_memory() / 1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("  Free: %d KB\n", (pmm_get_total_memory() - pmm_get_used_memory()) / 1024);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else if (strcmp(input_buffer, "reboot") == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Rebooting system...\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        outb(0x64, 0xFE);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (strlen(input_buffer) > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Unknown command: %s\n", input_buffer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Type 'help' for available commands.\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        buffer_pos = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("maya-os> ");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (c == '\b') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (buffer_pos > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        buffer_pos--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\b");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (c >= 32 && c <= 126) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (buffer_pos < 255) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        input_buffer[buffer_pos++] = c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("%c", c);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                